version: 2
general:
  branches:
    ignore:
      - master
jobs:
  build:
    docker:
      - image: circleci/golang:latest
        environment:
          NAISPLATER_VERSION: 4.0.0
          KUBECTL_IMAGE_TAG: v1.10.0
          NAISCAPER_VERSION: 29.0.0
    steps:
      - checkout
      - setup_remote_docker
      # nais-yaml + naisplater = <3
      - run:
          name: Run naisplater with nais-yaml
          command: |
            docker create -v /nais-yaml --name files0 alpine:3.4 /bin/true
            git clone https://${GH_TOKEN}@github.com/navikt/nais-yaml 2> /dev/null || echo "Failed to clone navikt/nais-yaml"
            docker cp `pwd`/nais-yaml files0:/
            docker run --name naisplater --volumes-from files0  navikt/naisplater:${NAISPLATER_VERSION} /bin/bash -c "naisplater ${CLUSTER_CONTEXT_NAME} /nais-yaml/templates /nais-yaml/vars /out ${ENC_KEY}" 2> /dev/null
            docker cp naisplater:/out naisplater-output
            ls -l naisplater-output
      # generate valid kubeconfig via gcloud cli
      - run: 
          name: Generate valid kubeconfig via gcloud cli
          command: |
            docker create -v /files --name files1 alpine:3.4 /bin/true
            openssl aes-256-cbc -d -md md5 -a -A -in `pwd`/${CLUSTER_NAME}-sa-credentials.json.enc -out `pwd`/sa-credentials.json -k ${ENC_KEY}
            docker cp `pwd`/sa-credentials.json files1:/files
            docker run --name gcloud --volumes-from files1 navikt/gcloud:1 bash -c "gcloud auth activate-service-account nais-ci@${GCP_PROJECT_NAME}.iam.gserviceaccount.com --key-file=/files/sa-credentials.json --project ${GCP_PROJECT_NAME};gcloud container clusters get-credentials ${CLUSTER_NAME} --zone europe-north1-a;kubectl get pods > /dev/null 2>&1"
            docker cp gcloud:/root/.kube/config kubeconfig
      # naiscaper

      - run:
          name: Run naiscaper
          command: |
            docker create -v /root/.kube/ -v /nais-platform-apps --name files3 alpine:3.4 /bin/true
            git clone https://${GH_TOKEN}@github.com/navikt/nais-platform-apps.git 2> /dev/null || echo "Failed to clone navikt/nais-platform-apps"
            docker cp `pwd`/nais-platform-apps files3:/
            docker cp `pwd`/kubeconfig files3:/root/.kube/config
            docker run -e HTTPS_PROXY="" --volumes-from files3 navikt/naiscaper:${NAISCAPER_VERSION} /bin/bash -c "/usr/bin/helm init --service-account=tiller --upgrade && /usr/bin/helm repo update && sleep 20 && naiscaper ${CLUSTER_CONTEXT_NAME} nais /nais-platform-apps"
      # kubectl apply yaml
      - run:
          name: kubectl apply various yaml-files
          command: |
            docker create -v /root/.kube/ -v /naisplater-output --name files2 alpine:3.4 /bin/true
            docker cp `pwd`/naisplater-output files2:/
            docker cp `pwd`/kubeconfig files2:/root/.kube/config
            docker run --name kubectl --volumes-from files2 lachlanevenson/k8s-kubectl:${KUBECTL_IMAGE_TAG} apply -f /naisplater-output
